[tool.poetry]
name = "regtech-data-validator"
version = "0.1.0"
description = "RegTech submission data parser and validator"
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pandas = "2.1.0"
pandera = "0.16.1"

[tool.poetry.group.dev.dependencies]
pytest = "7.4.0"
pytest-cov = "4.1.0"
black = "23.3.0"
ruff = "0.0.259"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# Black formatting
[tool.black]
preview = true
line-length = 120
skip-string-normalization = true
include = '\.pyi?$'
exclude = '''
/(
    | .devcontainer
    | .git          
    | .gitignore
    | .github
    | data
    | tools
  )/
'''

# Linting
[tool.ruff]
# Same as Black.
line-length = 120

# Testing
[tool.pytest.ini_options]
addopts = [
    "--cov-report=term-missing",
    "--cov-branch",
    "--cov-report=xml",
    "--cov-report=term",
    "--cov=regtech_data_validator",
    "-vv",
    "--strict-markers",
    "-rfE",
]
testpaths = [
    "tests",
]

[tool.coverage.run]
relative_files = true
source = ["regtech_data_validator"]

[tool.coverage.report]
skip_empty = true
